import Foundation

// MARK: - Evidence Confidence

/// How confident the engine is in an attribution decision.
/// Low-confidence evidence must never be presented as a certain result.
public enum FocusSessionEvidenceConfidence: String, Codable, Equatable, Sendable {
    /// The attribution is supported by clear, unambiguous evidence.
    case high
    /// The attribution relies on partial or indirect evidence;
    /// the session should be presented as tentative.
    case low
    /// Evidence is insufficient to determine attribution;
    /// the session is marked as unconfirmed, never silently counted.
    case pending
}

// MARK: - Rule Version

/// Identifies which version of the attribution rules produced the evidence.
/// Monotonic within a build; major bumps on incompatible changes.
public struct FocusSessionRuleVersion: Codable, Equatable, Sendable {
    public let major: Int
    public let minor: Int

    public static let current = FocusSessionRuleVersion(major: 1, minor: 0)

    public init(major: Int, minor: Int) {
        self.major = major
        self.minor = minor
    }
}

// MARK: - Attribution Source

/// Whether the project was chosen by foreground-app detection,
/// Git activity, or manual intervention.
public enum FocusSessionAttributionSource: String, Codable, Equatable, Sendable {
    case foregroundApp
    case gitActivity
    case manual
    case unknown
}

// MARK: - Project Attribution Explanation

/// Explains why a particular project was selected for a session.
/// Contains only redacted, presentation-safe identifiers.
public struct FocusSessionProjectAttribution: Codable, Equatable, Sendable {
    /// The display name (safe for UI).
    public let displayName: String
    /// How the project was selected.
    public let source: FocusSessionAttributionSource
    /// Confidence in this attribution.
    public let confidence: FocusSessionEvidenceConfidence
    /// Stable redacted identifier (SHA-256 prefix of repo path, or bundle ID).
    /// Never contains the full path, remote URL, or user-identifiable content.
    public let redactedIdentifier: String
    /// Human-readable explanation of why this project was selected.
    /// Deterministic: same inputs always produce the same text.
    public let explanation: String
    /// If confidence is low or pending, describes what is missing.
    public let caveat: String?

    public init(
        displayName: String,
        source: FocusSessionAttributionSource,
        confidence: FocusSessionEvidenceConfidence,
        redactedIdentifier: String,
        explanation: String,
        caveat: String? = nil
    ) {
        self.displayName = displayName
        self.source = source
        self.confidence = confidence
        self.redactedIdentifier = redactedIdentifier
        self.explanation = explanation
        self.caveat = caveat
    }
}

// MARK: - Detailed Decision Explanation

/// A single enriched decision record containing the full attribution chain.
/// Carries no full paths, commit content, remote URLs, or user input text.
public struct FocusSessionDecisionExplanation: Codable, Equatable, Sendable, Identifiable {
    public let id: UUID
    /// When the decision was made.
    public let at: Date
    /// What happened (started, paused, resumed, ended, etc.).
    public let kind: FocusSessionDecisionKind
    /// Primary reason for the decision.
    public let reason: FocusSessionDecisionReason
    /// Authority that produced the decision.
    public let source: FocusSessionDecisionSource
    /// Confidence for this specific decision.
    public let confidence: FocusSessionEvidenceConfidence
    /// Deterministic, human-readable explanation of this decision.
    /// Generated by the evidence engine; never includes raw input.
    public let explanation: String

    public init(
        id: UUID = UUID(),
        at: Date,
        kind: FocusSessionDecisionKind,
        reason: FocusSessionDecisionReason,
        source: FocusSessionDecisionSource,
        confidence: FocusSessionEvidenceConfidence,
        explanation: String
    ) {
        self.id = id
        self.at = at
        self.kind = kind
        self.reason = reason
        self.source = source
        self.confidence = confidence
        self.explanation = explanation
    }
}

// MARK: - Session Evidence

/// Full evidence record for one focus session.
/// Persisted alongside the session archive; atomically committed.
/// Ties every automatic decision back to a deterministic, explainable cause.
public struct FocusSessionEvidence: Codable, Equatable, Sendable, Identifiable {
    public let id: UUID
    /// The session this evidence belongs to.
    public let sessionID: UUID
    /// When this evidence record was created.
    public let createdAt: Date
    /// Rule version that produced this evidence.
    public let ruleVersion: FocusSessionRuleVersion
    /// Overall confidence for this session.
    public let confidence: FocusSessionEvidenceConfidence
    /// Project attribution explanation.
    public let projectAttribution: FocusSessionProjectAttribution
    /// Detailed explanations for each decision in the session lifecycle.
    public let decisionExplanations: [FocusSessionDecisionExplanation]

    public init(
        id: UUID = UUID(),
        sessionID: UUID,
        createdAt: Date,
        ruleVersion: FocusSessionRuleVersion = .current,
        confidence: FocusSessionEvidenceConfidence,
        projectAttribution: FocusSessionProjectAttribution,
        decisionExplanations: [FocusSessionDecisionExplanation]
    ) {
        self.id = id
        self.sessionID = sessionID
        self.createdAt = createdAt
        self.ruleVersion = ruleVersion
        self.confidence = confidence
        self.projectAttribution = projectAttribution
        self.decisionExplanations = decisionExplanations
    }
}

// MARK: - Evidence Archive

/// Versioned archive of evidence records, stored alongside `FocusSessionArchive`.
/// Same atomic write guarantees; schema-tied to the sessions they explain.
public struct FocusSessionEvidenceArchive: Codable, Equatable, Sendable {
    public static let currentSchemaVersion = 1

    public let schemaVersion: Int
    public let revision: Int64
    public let evidenceBySessionID: [UUID: FocusSessionEvidence]

    public init(
        schemaVersion: Int = Self.currentSchemaVersion,
        revision: Int64 = 0,
        evidenceBySessionID: [UUID: FocusSessionEvidence] = [:]
    ) {
        self.schemaVersion = schemaVersion
        self.revision = revision
        self.evidenceBySessionID = evidenceBySessionID
    }

    public var isSemanticallyValid: Bool {
        guard schemaVersion == Self.currentSchemaVersion,
              revision >= 0 else { return false }
        for (sessionID, evidence) in evidenceBySessionID {
            guard evidence.sessionID == sessionID else { return false }
            guard evidence.createdAt.timeIntervalSinceReferenceDate.isFinite else { return false }
        }
        return true
    }
}

// MARK: - Evidence Persistence

/// Abstraction over evidence persistence so the engine can be tested.
public protocol FocusSessionEvidencePersisting: Sendable {
    func loadEvidence() -> FocusSessionEvidenceArchive?
    @discardableResult func saveEvidence(_ archive: FocusSessionEvidenceArchive) -> Bool
}

/// Bundled archive combining sessions and their evidence for atomic writes.
/// This is the single persistence envelope used by the file store.
public struct FocusSessionBundledArchive: Codable, Equatable, Sendable {
    public static let currentSchemaVersion = 1

    public let schemaVersion: Int
    public let sessionArchive: FocusSessionArchive
    public let evidenceArchive: FocusSessionEvidenceArchive

    public init(
        schemaVersion: Int = Self.currentSchemaVersion,
        sessionArchive: FocusSessionArchive,
        evidenceArchive: FocusSessionEvidenceArchive
    ) {
        self.schemaVersion = schemaVersion
        self.sessionArchive = sessionArchive
        self.evidenceArchive = evidenceArchive
    }

    public var isSemanticallyValid: Bool {
        guard schemaVersion == Self.currentSchemaVersion,
              sessionArchive.isSemanticallyValid,
              evidenceArchive.isSemanticallyValid else { return false }
        // All evidence must reference existing sessions.
        for sessionID in evidenceArchive.evidenceBySessionID.keys {
            guard sessionArchive.sessions.contains(where: { $0.id == sessionID }) else {
                return false
            }
        }
        return true
    }
}
