#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP_DIR="${TMPDIR:-/private/tmp}"

export SWIFTPM_MODULECACHE_OVERRIDE="${SWIFTPM_MODULECACHE_OVERRIDE:-$TMP_DIR/tinybuddy-module-cache}"
export TINYBUDDY_SWIFTPM_CACHE_PATH="${TINYBUDDY_SWIFTPM_CACHE_PATH:-$TMP_DIR/tinybuddy-swiftpm-cache}"
export TINYBUDDY_SWIFTPM_CONFIG_PATH="${TINYBUDDY_SWIFTPM_CONFIG_PATH:-$TMP_DIR/tinybuddy-swiftpm-config}"
export TINYBUDDY_SWIFTPM_SECURITY_PATH="${TINYBUDDY_SWIFTPM_SECURITY_PATH:-$TMP_DIR/tinybuddy-swiftpm-security}"
export TINYBUDDY_SWIFTPM_SCRATCH_PATH="${TINYBUDDY_SWIFTPM_SCRATCH_PATH:-$ROOT_DIR/.build/spm}"

mkdir -p \
  "$SWIFTPM_MODULECACHE_OVERRIDE" \
  "$TINYBUDDY_SWIFTPM_CACHE_PATH" \
  "$TINYBUDDY_SWIFTPM_CONFIG_PATH" \
  "$TINYBUDDY_SWIFTPM_SECURITY_PATH" \
  "$TINYBUDDY_SWIFTPM_SCRATCH_PATH"
